version: 2
jobs:
  build:
    docker:
      # - image: circleci/node:6
      - image: circleci/node:8
      # - image: circleci/node:4.8
    working_directory: ~/flybook
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: fly-build
          command: npm run release
      - run:
          name: flybook gen
          command: npm run docs
      - run: git config --global user.email "rhio.kim@gmail.com"
      - run: git config --global user.name "Rhio Kim"
      - run:
          name: deploy docs
          command: npm run pages -- -m 'test'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: lint
          command: npm run lint
      - run:
          name: coverage
          command: npm run flow:coverage
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: feature/ci