version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/flybook
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: yarn install
      - run:
          name: generate docs
          command: yarn docs
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    steps:
      - checkout
      - run:
          name: lint
          command: npm run lint
      - run:
          name: coverage
          command: npm run flow:coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: feature/ci